export const PHOTO_PRIVACY_CONFIG = {
  sampleIntervalMs: 1_000,
  readinessSampleIntervalMs: 650,
  stableSampleIntervalMs: 1_000,
  resultFreshnessMs: 5_000,
  requiredAllowedStreak: 4,
  requiredBlockedStreak: 2,
  requiredFramingStreak: 2,
  uncertainThreshold: 0.10,
  blockedThreshold: 0.25,
  strongBlockedThreshold: 0.60,
  previewLongEdge: 224,
  framingLongEdge: 96,
  closeUpCenterToBorderEdgeRatio: 3,
  closeUpMinimumCenterEdgeCoverage: 0.08,
  closeUpMaximumBorderEdgeCoverage: 0.04,
  insufficientContextMaximumEdgeCoverage: 0.025,
  unstableFrameMeanDelta: 35,
  nearBlackLumaThreshold: 8,
  nearWhiteLumaThreshold: 248,
  minimumFrameVariance: 2,
  lowFrameVariance: 12,
  diagnosticSampleSize: 32,
  maximumLongEdge: 1_600,
  maximumBytes: 4 * 1024 * 1024,
  jpegQualities: [0.88, 0.82, 0.72] as const,
  inferenceTimeoutMs: 8_000,
  azureMinimumDimension: 50,
  azureMaximumDimension: 2_048,
  azureTimeoutMs: 10_000
} as const;
